require 'pythonism/classes/class'
require 'pythonism/classes/boolean'
require 'pythonism/classes/nil_class'
require 'pythonism/classes/string'
require 'pythonism/classes/fixnum'
require 'pythonism/classes/array'
